# Generated by Django 3.2 on 2023-06-11 22:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10, unique=True, verbose_name='Идентификатор')),
                ('iq_time', models.DateTimeField(blank=True, null=True, verbose_name='Время IQ')),
                ('iq_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Баллы')),
                ('eq_time', models.DateTimeField(blank=True, null=True, verbose_name='Время EQ')),
                ('eq_result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, null=True, size=5, verbose_name='Результат')),
            ],
        ),
    ]
